pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh """
                    python3 -m venv ${VENV}
                    source ${VENV}/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r Lessons/lesson_31/api_requirements.txt
                """
            }
        }


        stage('Run Auto-tests') {
            steps {
                sh """
                    source ${VENV}/bin/activate
                    pytest --junitxml=results.xml
                """
            }
        }

        stage('Publish Results') {
            steps {
                junit 'results.xml'
            }
        }
    }

    post {
        always {
            sh "rm -rf ${VENV}"
        }
    }
}
